#!/bin/bash

current_path=`pwd`

docker run --rm -e LOCAL_UID=$(id -u $USER) -e LOCAL_GID=$(id -g $USER) \
	--name pandoc_docker_vm  \
	-v ${current_path}:/mnt \
	pandoc_docker /usr/local/bin/entrypoin.sh "/bin/bash -c \"cd /mnt && bash pdfconv ${1}\""
